### PR TITLE
Transfer/Import additional chef-cookbooks

### PR DESCRIPTION
**Pull request by ramereth**
Signed-off-by: Lance Albertson <lance@osuosl.org>

## Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Review by Xorima — APPROVED** [review]

**Comment by Xorima** [comment]
Have you done the import @ramereth ?

**Comment by ramereth** [comment]
@Xorima not yet, I was going to do it next

**Comment by ramereth** [comment]
@Xorima should be imported now

**Review by Xorima — APPROVED** [review]
Looks great, merge time :+1:

**Pull request merged**
