### PR TITLE
Update main.tf with org_membership: add ibata

### PR DESCRIPTION
**Pull request by ibata**

### CODE REVIEW

**Comment by damacus** [comment]
Hey @ibata which cookbooks are you looking to contribute to?

**Comment by ibata** [comment]
the rundeck  cookbook

**Comment by damacus** [comment]
Cool. Want to add yourself as a maintainer of that too?

**Comment by damacus** [comment]
Hi @ibata could you update your PR and add ypurself to the rundeck maintainers please? 

If you could also pop into the #sous-chefs channel on the chef community slack that would also be grreat!



Welcome!

**Pull request merged**
