### PR TITLE
org_membership: add majormoses

### PR DESCRIPTION
**Pull request by majormoses**
Signed-off-by: Ben Abrams <me@benabrams.it>

## Description

adding majormoses (self)

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Hey! Anything in particular you're interested in helping with?

**Comment by majormoses** [comment]
I would probably be most interested in (no particular order):
- `openvpn`
- `java`
- `ruby_rbenv`
- `snort`
- `ruby_build`
- `graphite`
- `grafana`
- `mysql`
- `sysctl`
- `line-cookbook`

This list is non exhaustive but what I got really quick from looking, I also have some cookbooks that could potentially be brought into the org (such as the `redisio`). 

But the time I spend on these would be split on these as well as other OSS projects I maintain as well.

**Comment by tas50** [comment]
Feel free to add yourself where you think you'd be involved

**Comment by majormoses** [comment]
BTW I would also be interested in looking at helping with the TF management of the github repo itself.

**Comment by damacus** [comment]
Sounds awesome!

If you want to take an active role in any those. Just come along to the sous-chefs room in the chef community slack and I'll help get you started maintaining some of that stuff.

**Pull request merged**
