### PR TITLE
Add @jeffbyrnes to @sous-chefs & openvpn cookbook

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Per @damacus’s comment in sous-chefs/openvpn#121

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@damacus this is merged, and has a green check, but I do not seem to have any greater rights on the `openvpn` repo. Did I miss something?

**Comment by damacus** [comment]
There's probably an organisation invite in your inbox somewhere.
If it actually applied. 
I ran out of github.com api calls 😂

**Comment by jeffbyrnes** [comment]
Got it!

**Comment by damacus** [comment]
Good to hear! I replanned. Happy Bug hunting!

**Pull request merged**
