### PR TITLE
org_membership: add ronabop

### PR DESCRIPTION
**Pull request by ronabop**

### CODE REVIEW

**Comment by damacus** [comment]
Hey @ronabop which cookbooks are you looking to contribute to? 

Apologies this has been open so long!

**Comment by ronabop** [comment]
I occasionally make minor tweaks to rundeck, nrpe, mariadb, mostly cleanup/maintenance work .

**Comment by damacus** [comment]
Cool, if you wan to become a maintainer on any of those cookbooks, feel free to add yourself! We could use more maintainers

**Comment by damacus** [comment]
hi @ronabop could you update your PR to add yourself to this repositories please? And drop in on us in #sous-chefs on the chef community slack. 

Welcome!

**Pull request merged**
