### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by staj25**
org_membership: add staj25

## Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Hi there! 

Usually people drop by the sous-chef room in the Chef community slack or open an issue or two, before becoming a member. Closing this for now. 

Hopefully this is a welcome to the community! 🎉

**Comment by staj25** [comment]
> Hi there!
> 
> Usually people drop by the sous-chef room in the Chef community slack or open an issue or two, before becoming a member. Closing this for now.
> 
> Hopefully this is a welcome to the community! 🎉

Hi Damacus, 

Sorry I was just following the membership guidelines I found on the site? I'm new to the Chef/DevOps World and am hoping to become actively knowledgeable, that's why I joined. Can you please give me some advise on how to proceed? Thanks.

**Comment by damacus** [comment]
Sneakily hidden below the title:

Join us on the [Chef community slack](https://chefcommunity.slack.com/messages/sous-chefs/), and say hi!

That's the best place to start. Secondly if you don't like slack, then just opening fixing a few bugs and getting known by community members is a great place to start.

**Comment by staj25** [comment]
Thanks, I'm just in timid and sceptical mode at the moment as I'm still new at this and I'm not sure how I'm going to be of use here. I've setup access to the slack community so I'll take your advise and say hi. 

With respect to "opening fixing" I'm guessing you mean bugs that I encounter as I use chef. If so, I don't currently use it enough especially as my current team doesn't deal with such operations, so I was hoping joining the community and being of use here would help.

**Comment by damacus** [comment]
Sounds great, drop in on the Chef Community Slack and I'm sure we can point you in the right direction if you want to help with something 👍

**Comment by staj25** [comment]
Thanks a lot, I'm grateful for your feedback.

**Pull request closed without merging**
