### PR TITLE
add member anuriq

### PR DESCRIPTION
**Pull request by anuriq**

### CODE REVIEW

**Comment by damacus** [comment]
Welcome!

Would you like to maintain any repo in particular?

If so add yourself to that repos terraform file too and I'll merge away.

**Comment by anuriq** [comment]
Right now, I just wanted to become a member. Later, I'll try to engage with cookbooks. Thank you @damacus

**Comment by anuriq** [comment]
@damacus are there any problems?

**Comment by damacus** [comment]
To be honest you'll get the same membership without doing this bit.

All we ask is you join us in slack for conversations and try to submit prs.

Maybe we should make this more clear?

**Comment by anuriq** [comment]
Hi there. I need to become a member to transfer the cookbook https://github.com/parallels-cookbooks/confluence to sous-chefs

**Comment by damacus** [comment]
I've reapplied terraform on the master branch and this has now actually added you. We've have a small problem with Terraform Enterprise not working right now  👍  (but it's been done manually now)

**Pull request closed without merging**
